const complexBusinesses = [
  {
    id: "sago",
    name: "SAGO Gas Bar",
    address: "39 Dundas Street",
    blurbEn: "Full-service regular, premium, and diesel.",
    blurbFr: "Essence ordinaire, super et diesel en service complet.",
    href: "/gas-station-deseronto",
    external: false,
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJh8jI5dDW14kRkWuKCAVsMeA",
    schemaType: "GasStation",
    telephone: "+1-613-396-2224",
  },
  {
    id: "lnm",
    name: "L&M Enterprises",
    address: "43 Dundas Street",
    blurbEn: "Convenience store, tobacco, vapes, and snacks.",
    blurbFr: "D\u00e9panneur, tabac, vapotage et collations.",
    href: "/",
    external: false,
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJ6wH13dDW14kRdfm-TgSpygU",
    schemaType: "ConvenienceStore",
    telephone: "+1-613-396-2224",
  },
  {
    id: "medibles",
    name: "Mohawk Medibles",
    address: "45 Dundas Street",
    blurbEn: "Licensed cannabis store next door.",
    blurbFr: "Magasin de cannabis autoris\u00e9, juste \u00e0 c\u00f4t\u00e9.",
    href: "https://mohawkmedibles.ca/",
    external: true,
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJUa3RTdDW14kRUbQUjhh1AWg",
    schemaType: "Store",
    telephone: "+1-613-396-6728",
  },
  {
    id: "stonedchef",
    name: "The Stoned Chef",
    address: "45 Dundas Street",
    blurbEn: "Restaurant in the same building.",
    blurbFr: "Restaurant dans le m\u00eame b\u00e2timent.",
    href: "https://thestonedchef.ca/",
    external: true,
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJM1QSLofX14kRYhjfsl2gC6Y",
    schemaType: "Restaurant",
    telephone: "+1-343-337-5810",
  },
];

module.exports = { complexBusinesses };
